### ISSUE TITLE
ESMF examples

### ISSUE THREAD

**Issue by jhamman** [NCAR/lilac#10]
I thought it would be useful to collect a few relevant ESMF examples.

@rsdunlapiv provided this one:

- Here is an example code showing use of plain ESMF to couple two components: https://sourceforge.net/p/esmf/external_demos/ci/master/tree/ESMF_CoupledFlow/

**Comment by billsacks** [comment]
@jhamman thanks, it is useful to collect these together. I wonder, though, if they should go on the wiki rather than in an issue?

**Comment by jhamman** [comment]
Let's move them to the wiki after collecting them. i'm generally not a fan of wikis but they are good for a few things.

**Comment by billsacks** [comment]
Created wiki page: https://github.com/NCAR/lilac/wiki/ESMF-examples
