### ISSUE TITLE
ESMF test fixtures

### ISSUE THREAD

**Issue by jhamman** [NCAR/lilac#3]
In a recent meeting, we discussed using ESMF test fixtures for LILAC testing. I'm hoping @rsdunlapiv can help point me in the right direction here. 

Basically, I want to setup small test atmosphere and land components and pass fields between them using LILAC. My understanding is that there are some utilities in ESMF that makes the component setup relatively easy.

**Comment by jhamman** [comment]
See also: http://www.earthsystemmodeling.org/esmf_releases/last_built/ESMF_refdoc/node5.html#SECTION050104600000000000000

**Comment by billsacks** [comment]
I think this is no longer needed, given the directions we've gone for testing.
