### ISSUE TITLE
Github Projects for LILAC

### ISSUE THREAD

**Issue by jhamman** [NCAR/lilac#6]
@negin513 suggested we develop a project board for the LILAC project. I looked into this a bit (and even started one in this project). LILAC being an interface project is going to need to coordinate issues across multiple repositories and across multiple Github Organizations (e.g. ESCOMP and NCAR). It turns out the inter-org problem is not something Github supports so I have the following proposal.

1. we use the LILAC projects tab to coordinate LILAC development
1. we open sister issues in the CTSM and LILAC repos where coordination needs to be done
1. we have a tag on issues in both CTSM and LILAC that highlight they are for coordination with the other project

thoughts @billsacks?

**Comment by billsacks** [comment]
Sounds good.

**Comment by billsacks** [comment]
I have added "tag: lilac" in the CTSM repo, and colored it lilac :-)

**Comment by billsacks** [comment]
Closing because this has been resolved.
